name: Check domains

on:
  schedule:
    - cron:  '*/1 * * * *'

jobs:
  hello:
    runs-on: ubuntu-latest
    name: Check domain
    strategy:
      matrix:
        domain:
          - https://codex.so
          - https://editorjs.io
    steps:
      - name: Check domain SSL and registry expire date
        id: check-domain
        uses: codex-team/action-check-domain@v1
        with:
          url: ${{ matrix.domain }}
